/**
 * OmniCore Model and State Management API
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: omnicoresupport@korewireless.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListSinksSinksInnerConfig model module.
 * @module model/ListSinksSinksInnerConfig
 * @version 1.0
 */
class ListSinksSinksInnerConfig {
    /**
     * Constructs a new <code>ListSinksSinksInnerConfig</code>.
     * @alias module:model/ListSinksSinksInnerConfig
     */
    constructor() { 
        
        ListSinksSinksInnerConfig.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListSinksSinksInnerConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListSinksSinksInnerConfig} obj Optional instance to populate.
     * @return {module:model/ListSinksSinksInnerConfig} The populated <code>ListSinksSinksInnerConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListSinksSinksInnerConfig();

            if (data.hasOwnProperty('connectionParameter')) {
                obj['connectionParameter'] = ApiClient.convertToType(data['connectionParameter'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListSinksSinksInnerConfig</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListSinksSinksInnerConfig</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['connectionParameter'] && !(typeof data['connectionParameter'] === 'string' || data['connectionParameter'] instanceof String)) {
            throw new Error("Expected the field `connectionParameter` to be a primitive type in the JSON string but got " + data['connectionParameter']);
        }

        return true;
    }


}



/**
 * @member {String} connectionParameter
 */
ListSinksSinksInnerConfig.prototype['connectionParameter'] = undefined;






export default ListSinksSinksInnerConfig;

