/**
 * OmniCore Model and State Management API
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.13
 * Contact: omnicoresupport@korewireless.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MetricsLogs from './MetricsLogs';

/**
 * The MetricsData model module.
 * @module model/MetricsData
 * @version 1.8.13
 */
class MetricsData {
    /**
     * Constructs a new <code>MetricsData</code>.
     * @alias module:model/MetricsData
     */
    constructor() { 
        
        MetricsData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetricsData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetricsData} obj Optional instance to populate.
     * @return {module:model/MetricsData} The populated <code>MetricsData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetricsData();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [MetricsLogs]);
            }
            if (data.hasOwnProperty('TotalExportSize')) {
                obj['TotalExportSize'] = ApiClient.convertToType(data['TotalExportSize'], 'Number');
            }
            if (data.hasOwnProperty('TotalReplaySize')) {
                obj['TotalReplaySize'] = ApiClient.convertToType(data['TotalReplaySize'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MetricsData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MetricsData</code>.
     */
    static validateJSON(data) {
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                MetricsLogs.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/MetricsLogs>} data
 */
MetricsData.prototype['data'] = undefined;

/**
 * @member {Number} TotalExportSize
 */
MetricsData.prototype['TotalExportSize'] = undefined;

/**
 * @member {Number} TotalReplaySize
 */
MetricsData.prototype['TotalReplaySize'] = undefined;






export default MetricsData;

