/**
 * OmniCore Model and State Management API
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.20
 * Contact: omnicoresupport@korewireless.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SetRetentionBody model module.
 * @module model/SetRetentionBody
 * @version 1.8.20
 */
class SetRetentionBody {
    /**
     * Constructs a new <code>SetRetentionBody</code>.
     * @alias module:model/SetRetentionBody
     */
    constructor() { 
        
        SetRetentionBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SetRetentionBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SetRetentionBody} obj Optional instance to populate.
     * @return {module:model/SetRetentionBody} The populated <code>SetRetentionBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetRetentionBody();

            if (data.hasOwnProperty('retentionPeriod')) {
                obj['retentionPeriod'] = ApiClient.convertToType(data['retentionPeriod'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SetRetentionBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SetRetentionBody</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['retentionPeriod'] && !(typeof data['retentionPeriod'] === 'string' || data['retentionPeriod'] instanceof String)) {
            throw new Error("Expected the field `retentionPeriod` to be a primitive type in the JSON string but got " + data['retentionPeriod']);
        }

        return true;
    }


}



/**
 * @member {String} retentionPeriod
 */
SetRetentionBody.prototype['retentionPeriod'] = undefined;






export default SetRetentionBody;

